### ISSUE TITLE
Docker Image: appwrite/appwrite-lite is NOT public

### ISSUE THREAD

**Issue by jayjah** [appwrite/lite#12]
> Pulling appwrite-lite (appwrite/appwrite-lite:)...
> ERROR: pull access denied for appwrite/appwrite-lite, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

That image is not visisible on [AppWrite Dockerhub](https://hub.docker.com/u/appwrite)!

**Comment by TorstenDittmann** [comment]
Hey,

That's is true. We are still working on this version right now and will be published soon 🙂

**Comment by jayjah** [comment]
Ahh ok I see. I thought it would be available at the moment. Thanks for the info!
