### ISSUE TITLE
Release date

### ISSUE THREAD

**Issue by doricci** [appwrite/lite#13]
Hello,

First of all, thank you on working on a lite version of appwrite! 

Then is there any estimate on when this version will be public? 

Regards

**Comment by eldadfux** [comment]
For now it seems like we're not be able to make Functions work on Heroku, we're working to introduce a few new env options to disable different services and allow a slimmer setup. Hard to say exactly ho much time it will take, my guess is a few weeks, but the most important thin is that we're actively working on it :)

**Comment by doricci** [comment]
@eldadfux Thank you very much for the answer, I'm really looking forward to see this lite version of appwrite being released :) 
For now I'll continue with the normal version :)
